language: python
python:
    - 2.7
cache: pip
before_install:
    - pip install -e .
    - pip install coverage flake8
script:
    - flake8
    - coverage run `while trial` vumi_unidecode_middleware
after_success:
    - pip install coveralls
    - coveralls
